# Generated by Django 4.2 on 2023-05-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('gender', models.BooleanField(choices=[(1, 'male'), (0, 'female')])),
                ('id_card', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
            ],
            options={
                'permissions': (),
            },
        ),
    ]
