# Generated by Django 4.2 on 2023-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikihow_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="gender", field=models.BooleanField(),
        ),
    ]
