# Generated by Django 4.2 on 2023-05-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wikihow_app", "0002_alter_person_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=255)),
                ("thumbnail", models.CharField(max_length=255)),
                ("views", models.CharField(max_length=255)),
                ("release_date", models.CharField(max_length=32)),
                ("author", models.CharField(max_length=32)),
                ("description", models.CharField(max_length=255)),
                ("text", models.CharField(max_length=255)),
                ("num_sections", models.IntegerField()),
                ("num_images", models.IntegerField()),
            ],
        ),
    ]
